version: '3.7'

services:
  db:
    image: postgres
    container_name: gear_db
    volumes:
      - gear_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD
    networks:
      - network

  app:
    container_name: gear_app
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/gear_app
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - CLIENT_ID
      - CLIENT_SECRET
      - AUTHORIZATION_CODE
      - DB_USER
      - DB_PASSWORD
      - POSTGRES_PASSWORD
      - DB_HOST
      - URL
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  gear_data:
