# Generated by Django 4.0.2 on 2022-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect_type", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=50)),
                ("object_id", models.CharField(max_length=200)),
                ("owner_id", models.CharField(max_length=200)),
                ("subscription_id", models.CharField(max_length=200)),
                ("event_time", models.IntegerField()),
                ("updates", models.JSONField()),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
