name: Code Quality Checks
on: [push]
jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - run: docker compose -f docker-compose-gha.yml build app
      - run: docker compose -f docker-compose-gha.yml run app "isort --check-only .; black --check ."