name: Code Quality Checks
on: [push]
jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - run: ls
      - run: docker compose -f docker-compose-gha.yml build app